/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficas;
import javax.swing.JOptionPane;
import javax.swing.tree.*;
/**
 *
 * @author personal Ricardo Millon
 */
public class JTree extends javax.swing.JDialog {

    private  DefaultMutableTreeNode titulo;
    private DefaultTreeModel modelo;
    
    public JTree(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Arbol.setModel(cargarArbol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Arbol = new javax.swing.JTree();
        btnAgregar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnInformacion = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(Arbol);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnInformacion.setText("Informacion");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(btnInformacion)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnRemover)
                    .addComponent(btnInformacion)
                    .addComponent(btnModificar))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String cadena = JOptionPane.showInputDialog(this,"Ingrese un apartamento: ");
        DefaultMutableTreeNode parentNodo;
        TreePath parePath = Arbol.getSelectionPath();
        if(parePath == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento!!");
        }else{
            parentNodo = (DefaultMutableTreeNode) parePath.getLastPathComponent();
            DefaultMutableTreeNode child = new DefaultMutableTreeNode(cadena);
            modelo.insertNodeInto(child, parentNodo, parentNodo.getChildCount());
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode parentNode;
        TreePath currentSelection = Arbol.getSelectionPath();
        if(currentSelection != null){
            parentNode = (DefaultMutableTreeNode) currentSelection.getLastPathComponent();
            DefaultTreeModel model = (DefaultTreeModel) Arbol.getModel();
            model.removeNodeFromParent(parentNode);
        }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) Arbol.getLastSelectedPathComponent();
        if(node == null){
            return;
        }
        Object noteinfo = node.getUserObject();
        JOptionPane.showMessageDialog(this, noteinfo.toString());
            
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) Arbol.getLastSelectedPathComponent();
        if(node == null){
            return;
        }
        Object noteinfo = node.getUserObject();
        String cadena = JOptionPane.showInputDialog(this,"Ingrese el nuevo nombre", noteinfo.toString());
        TreePath currentSelection = Arbol.getSelectionPath();
        if(currentSelection != null){
            node = (DefaultMutableTreeNode) currentSelection.getLastPathComponent();
            node.setUserObject(cadena);
            DefaultTreeModel model = ((DefaultTreeModel) Arbol.getModel());
            model.nodeChanged(node);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

   public DefaultTreeModel cargarArbol(){
       titulo = new DefaultMutableTreeNode("Centro de administracion");
       modelo = new DefaultTreeModel(titulo);
       DefaultMutableTreeNode categorias = new DefaultMutableTreeNode("Adm.Redes");
       DefaultMutableTreeNode subcategorias = new DefaultMutableTreeNode("Dep.Planificacion");
       modelo.insertNodeInto(categorias, titulo, 0);
       modelo.insertNodeInto(subcategorias, categorias, 0);
       categorias = new DefaultMutableTreeNode("Adm.Laboratorio");
       subcategorias = new DefaultMutableTreeNode("Dept.de tecnologia");
       modelo.insertNodeInto(categorias, titulo, 1);
       modelo.insertNodeInto(subcategorias, categorias, 0);
       categorias = new DefaultMutableTreeNode("Dept. Investigacion");
       subcategorias = new DefaultMutableTreeNode("Dept.A");
       modelo.insertNodeInto(categorias, titulo, 2);
       modelo.insertNodeInto(subcategorias, categorias, 0);
       return modelo;

   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Arbol;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
