
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author personal
 */
public class reporteApa extends javax.swing.JDialog {

    /**
     * Creates new form reporteApa
     */
    public reporteApa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarComboDepa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbDEPA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnMostrar.setText("Mostrar el reporte");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Escoja el dapartamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDEPA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(cmbDEPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnSalir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int lineasTotales;
    static int totalCoincidencias;
    
    public static void buscarPalabra(File archivo, String Departamento) {
        try {
            
            if(archivo.exists()) {
                
                BufferedReader leerArchivo = new BufferedReader(new FileReader(archivo));
               
                String lineaLeida;
                 JOptionPane.showMessageDialog(null, "*******Leyendo Archivo*************");
               
                while((lineaLeida = leerArchivo.readLine()) != null) {
                    lineasTotales = lineasTotales + 1;
                    String[] palabras = lineaLeida.split(",");
                    for(int i = 0 ; i < palabras.length ; i++) {
                        if(palabras[i].equals(Departamento)) {
                            totalCoincidencias = totalCoincidencias + 1;
                            
                            JOptionPane.showMessageDialog(null, "Cedula: " + palabras[0] + "\n"
                                    + "Nombre: " + palabras[1] + "\n" + "Genero: " + palabras[2] + "\n"
                                    + "Departamento: " + palabras[3] + "\n" + "Fecha de nacimiento: "
                                    + palabras[4] + "\n" + "Edad: " + palabras[5] + "\n"
                                    + "Ingreso a la empresa: " + palabras[6] + "\n"
                                    + "Nivel de ingles: " + palabras[7] + "\n"
                                    + "Puesto: " + palabras[8]
                            );

 
                            JOptionPane.showMessageDialog(null,"**********");
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(null,"En total se encotro el departamento: " +Departamento + ", " + totalCoincidencias + " Veces en la base de datos");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
 
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here
          
        File register = new File("Datos.txt");
        String seleccion = (String) cmbDEPA.getSelectedItem();
        buscarPalabra(register,seleccion);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

      String ruta = "C:\\TXT";
  private void llenarComboDepa() {
        try {

            File archivo;
            FileReader fr;
            BufferedReader br;
            archivo = new File(ruta, "Departamentos.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            String p;
            String linea = br.readLine();
            while (linea != null) {

                String[] campoLinea = linea.split(",");
                p = campoLinea[0].trim();
                linea = br.readLine();

                cmbDEPA.addItem(p);
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, detalles: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbDEPA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
