/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Presentacion.FrmLogin;
/**
 *
 * @author personal
 */
public class FrmMenu extends javax.swing.JFrame {
  
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        ManteAerolinea = new javax.swing.JRadioButtonMenuItem();
        MantTripula = new javax.swing.JRadioButtonMenuItem();
        ManteAviones = new javax.swing.JRadioButtonMenuItem();
        ManteAeropuertos = new javax.swing.JRadioButtonMenuItem();
        ManteVuelos = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        vuelos = new javax.swing.JCheckBoxMenuItem();
        rankinAviones = new javax.swing.JCheckBoxMenuItem();
        intripulantes = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem7.setSelected(true);
        jRadioButtonMenuItem7.setText("jRadioButtonMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Opciones");

        ManteAerolinea.setSelected(true);
        ManteAerolinea.setText("Mantenimiento de aerolíneas");
        ManteAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManteAerolineaActionPerformed(evt);
            }
        });
        jMenu3.add(ManteAerolinea);

        MantTripula.setSelected(true);
        MantTripula.setText("Mantenimiento de tripulaciones");
        MantTripula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantTripulaActionPerformed(evt);
            }
        });
        jMenu3.add(MantTripula);

        ManteAviones.setSelected(true);
        ManteAviones.setText("Mantenimiento de aviones");
        ManteAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManteAvionesActionPerformed(evt);
            }
        });
        jMenu3.add(ManteAviones);

        ManteAeropuertos.setSelected(true);
        ManteAeropuertos.setText("Mantenimiento de aeropuertos");
        ManteAeropuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManteAeropuertosActionPerformed(evt);
            }
        });
        jMenu3.add(ManteAeropuertos);

        ManteVuelos.setSelected(true);
        ManteVuelos.setText("Mantenimiento de vuelos");
        ManteVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManteVuelosActionPerformed(evt);
            }
        });
        jMenu3.add(ManteVuelos);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Reportes");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Vuelos por fecha");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem2);

        vuelos.setSelected(true);
        vuelos.setText("Vuelos por Aerolineas");
        vuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelosActionPerformed(evt);
            }
        });
        jMenu5.add(vuelos);

        rankinAviones.setSelected(true);
        rankinAviones.setText("Ranking de aviones");
        rankinAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankinAvionesActionPerformed(evt);
            }
        });
        jMenu5.add(rankinAviones);

        intripulantes.setSelected(true);
        intripulantes.setText("información de Tripulantes");
        intripulantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intripulantesActionPerformed(evt);
            }
        });
        jMenu5.add(intripulantes);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Cerrar sesión");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManteAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManteAerolineaActionPerformed
        // TODO add your handling code here:
        JDAerolineas log = new JDAerolineas(this, true);
        log.pack();
        log.setVisible(true);
        
     
    }//GEN-LAST:event_ManteAerolineaActionPerformed

    private void MantTripulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantTripulaActionPerformed
        JDTripulacion log = new JDTripulacion(this, true);
        log.pack();
        log.setVisible(true);
       
    }//GEN-LAST:event_MantTripulaActionPerformed

    private void ManteAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManteAvionesActionPerformed
        // TODO add your handling code here:
     JDAvion log = new JDAvion(this, true);
     log.pack();
     log.setVisible(true);
     
    }//GEN-LAST:event_ManteAvionesActionPerformed

    private void ManteAeropuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManteAeropuertosActionPerformed
        // TODO add your handling code here:
        JDAeropuertos log = new JDAeropuertos(this, true);
        log.pack();
        log.setVisible(true);
        
    }//GEN-LAST:event_ManteAeropuertosActionPerformed

    private void ManteVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManteVuelosActionPerformed
        // TODO add your handling code here:
        JDVuelos log = new JDVuelos(this, true);
        log.pack();
        log.setVisible(true);
        
    }//GEN-LAST:event_ManteVuelosActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
         dispose();
         JFMenuPrincipal log = new JFMenuPrincipal();
         log.pack();
         log.setVisible(true);
        
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        JDRepoFecha log = new JDRepoFecha(this, true);
        log.pack();
        log.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void vuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelosActionPerformed
        // TODO add your handling code here:
        JDReAerolinea log = new JDReAerolinea(this, true);
        log.pack();
        log.setVisible(true);
       
    }//GEN-LAST:event_vuelosActionPerformed

    private void intripulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intripulantesActionPerformed
        // TODO add your handling code here:
        JDiNFORMACIONtRIPULANTES log = new JDiNFORMACIONtRIPULANTES(this, true);
        log.pack();
        log.setVisible(true);
    }//GEN-LAST:event_intripulantesActionPerformed

    private void rankinAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankinAvionesActionPerformed
        // TODO add your handling code here:
        JDRankingAviones log = new JDRankingAviones(this, true);
        log.pack();
        log.setVisible(true);
    }//GEN-LAST:event_rankinAvionesActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem MantTripula;
    private javax.swing.JRadioButtonMenuItem ManteAerolinea;
    private javax.swing.JRadioButtonMenuItem ManteAeropuertos;
    private javax.swing.JRadioButtonMenuItem ManteAviones;
    private javax.swing.JRadioButtonMenuItem ManteVuelos;
    private javax.swing.JCheckBoxMenuItem intripulantes;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JCheckBoxMenuItem rankinAviones;
    private javax.swing.JCheckBoxMenuItem vuelos;
    // End of variables declaration//GEN-END:variables
}
