/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author personal
 */
public class JDEscojerVuelo extends javax.swing.JDialog {

    /**
     * Creates new form JDEscojerVuelo
     */
    public JDEscojerVuelo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnOpciones = new javax.swing.JMenu();
        buscarvueloInteligente = new javax.swing.JCheckBoxMenuItem();
        cmbHistorial = new javax.swing.JCheckBoxMenuItem();
        btnCerrarse = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOpciones.setText("Opciones");

        buscarvueloInteligente.setSelected(true);
        buscarvueloInteligente.setText("Escojer vuelos");
        buscarvueloInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarvueloInteligenteActionPerformed(evt);
            }
        });
        btnOpciones.add(buscarvueloInteligente);

        cmbHistorial.setSelected(true);
        cmbHistorial.setText("Historial de vuelos");
        cmbHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHistorialActionPerformed(evt);
            }
        });
        btnOpciones.add(cmbHistorial);

        jMenuBar1.add(btnOpciones);

        btnCerrarse.setText("Cerrar Sesión");
        btnCerrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarseMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnCerrarse);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHistorialActionPerformed
        // TODO add your handling code here:
        JDhistorial log = new JDhistorial(null, true);
        log.pack();
        log.setVisible(true);
        
    }//GEN-LAST:event_cmbHistorialActionPerformed

    private void buscarvueloInteligenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarvueloInteligenteActionPerformed
        // TODO add your handling code here:
        JDVuelopasa log = new JDVuelopasa(null, true);
        log.pack();
        log.setVisible(true);
    }//GEN-LAST:event_buscarvueloInteligenteActionPerformed

    private void btnCerrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarseMouseClicked
        // TODO add your handling code here:
        dispose();
        JFMenuPrincipal log = new JFMenuPrincipal();
         log.pack();
         log.setVisible(true);
    }//GEN-LAST:event_btnCerrarseMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnCerrarse;
    private javax.swing.JMenu btnOpciones;
    private javax.swing.JCheckBoxMenuItem buscarvueloInteligente;
    private javax.swing.JCheckBoxMenuItem cmbHistorial;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
