/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Herencias;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author personal
 */
public class buscar extends javax.swing.JDialog {

    /**
     * Creates new form buscar
     */
    public buscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtBuscarPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Numero de placa");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(37, 37, 37)
                        .addComponent(btnSalir))
                    .addComponent(txtBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnSalir))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed
     static int lineasTotales;
    static int totalCoincidencias;
    
    private String buscar(File fichero , String placa){
        String registro = null;
        
        try {
            if(fichero.exists()){
                BufferedReader lector = new BufferedReader (new FileReader(fichero));
                String linea;
                
               
                
                while((linea = lector.readLine()) != null){
                    JOptionPane.showMessageDialog(null, "Buscando el numero de placa: " + linea );
                    
                    
                    String[] datos = linea.split(",");
   
                    for(int i = 0 ; i < datos.length ; i++) {
                        if(datos[i].equals(datos)) {
                            totalCoincidencias = totalCoincidencias + 1;
                            System.out.println(linea);
                            System.out.println("En la linea: " + lineasTotales + " se encontro la palabra a buscar: " + datos);
                            System.out.println("");
                        break;
                        
                    }
                    }
                }
                
                JOptionPane.showMessageDialog(null, "*****Fin de la busqueda****");
                lector.close();
                
            }else{
                 JOptionPane.showMessageDialog(null, "El archivo no existe !!!");
            }
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return registro;
    }
    
    public static void buscarPalabra(File archivo, String placa) {
        try {
            
            if(archivo.exists()) {
                
                BufferedReader leerArchivo = new BufferedReader(new FileReader(archivo));
               
                String lineaLeida;
                 JOptionPane.showMessageDialog(null, "*******Leyendo Archivo*************");
               
                while((lineaLeida = leerArchivo.readLine()) != null) {
                    lineasTotales = lineasTotales + 1;
                    String[] palabras = lineaLeida.split(" ");
                    for(int i = 0 ; i < palabras.length ; i++) {
                        if(palabras[i].equals(placa)) {
                            totalCoincidencias = totalCoincidencias + 1;
                            JOptionPane.showMessageDialog(null,lineaLeida);
                            JOptionPane.showMessageDialog(null,"En la linea: " + lineasTotales + " se encontro la palabra a buscar: " + placa);
                            JOptionPane.showMessageDialog(null,"*****Fin del Archivo*****");
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(null,"En total se encotro la placa: " +placa + ", " + totalCoincidencias + " Veces en el archivo");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
 
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        
        File register = new File("C:\\TXT\\carro.txt");
        buscarPalabra(register,txtBuscarPlaca.getText());
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBuscarPlaca;
    // End of variables declaration//GEN-END:variables
}
